plugins:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup

title:            Nikhil Mehta

tagline:          'RA at IIT-Kanpur'

description:      'Research Assistant<br>
                  Computer Engineering<br>
                  IIT-Kanpur <br>
                  <a href="mailto:nikhilm@iitk.ac.in">nikhilm@iitk.ac.in</a>'
 
#description:      'Alright then <a href="http://jekyllrb.com" target="_blank">Jekyll</a> the<a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://nikhil-dce.github.io
baseurl:          /

author:
  name:           'Nikhil Mehta'
  url:            https://twitter.com/_nikhilmehta

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nikhil-dce
  page:           https://nikhil-dce.github.io

